In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split

#### Escalamiento de los datos

In [3]:
#Cargamos la base de datos
x = pd.read_csv('dataEntreno.csv')
x.head()

production_budget  worldwide_gross   title_year  aspect_ratio    duration  \
0        425000000.0     2.783919e+09  2009.000000      1.780000  178.000000   
1        306000000.0     2.058662e+09  2002.102628      2.126683  108.552703   
2        300000000.0     9.634204e+08  2007.000000      2.350000  169.000000   
3        300000000.0     8.796209e+08  2015.000000      2.350000  148.000000   
4        275000000.0     1.084439e+09  2012.000000      2.350000  164.000000   

   cast_total_facebook_likes        budget  imdb_score         gross  
0                     4834.0  2.370000e+08         7.9  7.605058e+08  
1                      143.0  3.712339e+07         7.1  4.819001e+07  
2                    48350.0  3.000000e+08         7.1  3.094042e+08  
3                    11700.0  2.450000e+08         6.8  2.000742e+08  
4                   106759.0  2.500000e+08         8.5  4.481306e+08

In [4]:
#Extraemos nuestra variable target
y = x['worldwide_gross']
#Eliminamos la variable de nuestra base
x.drop('worldwide_gross',axis=1,inplace=True)
x.tail()

production_budget  title_year  aspect_ratio  duration  \
4056             7000.0      2004.0      1.850000      77.0   
4057             7000.0      2005.0      2.126683      80.0   
4058             7000.0      2005.0      2.126683      84.0   
4059             3967.0      2012.0      2.350000     100.0   
4060             1100.0      2004.0      1.850000      90.0   

      cast_total_facebook_likes        budget  imdb_score         gross  
4056                      368.0  7.000000e+03         7.0  4.247600e+05  
4057                        0.0  7.000000e+03         6.3  7.007100e+04  
4058                       93.0  3.250000e+03         7.8  4.819001e+07  
4059                     2386.0  3.712339e+07         6.3  1.044300e+04  
4060                      163.0  1.100000e+03         6.6  8.522200e+04

In [5]:
#Creamos nuestos tabulares y features(target) de entreno y de prueba
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [6]:
#El 75% es para entreno y el 25% para prueba
len(x_train)/len(x)

0.7498153164245259

Existen distintas estrategias de escalamiento de tus features, pero la más común es la estandarización donde convertimos la variable para que la distribución de esta siga una distribución que es Gaussiana de media 0 y de desviación estandar 1.

In [7]:
from sklearn.preprocessing import StandardScaler
#Instancio el estimador
scaler = StandardScaler()
#Entreno el estimador
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
#Hiperparametro
scaler.mean_

array([3.34547374e+07, 2.00209762e+03, 2.13191743e+00, 1.08914606e+02,
       1.01700056e+04, 3.68931467e+07, 6.47665025e+00, 4.87418045e+07])

In [9]:
scaler.scale_

array([4.15348276e+07, 1.21539416e+01, 7.66392784e-01, 2.35801926e+01,
       1.58619667e+04, 6.13814409e+07, 1.06834891e+00, 6.51414719e+07])

In [10]:
x.values

array([[4.25000000e+08, 2.00900000e+03, 1.78000000e+00, ...,
        2.37000000e+08, 7.90000000e+00, 7.60505847e+08],
       [3.06000000e+08, 2.00210263e+03, 2.12668290e+00, ...,
        3.71233913e+07, 7.10000000e+00, 4.81900113e+07],
       [3.00000000e+08, 2.00700000e+03, 2.35000000e+00, ...,
        3.00000000e+08, 7.10000000e+00, 3.09404152e+08],
       ...,
       [7.00000000e+03, 2.00500000e+03, 2.12668290e+00, ...,
        3.25000000e+03, 7.80000000e+00, 4.81900113e+07],
       [3.96700000e+03, 2.01200000e+03, 2.35000000e+00, ...,
        3.71233913e+07, 6.30000000e+00, 1.04430000e+04],
       [1.10000000e+03, 2.00400000e+03, 1.85000000e+00, ...,
        1.10000000e+03, 6.60000000e+00, 8.52220000e+04]])

In [11]:
scaler.transform(x_train)

array([[-0.14336733, -1.57131096,  0.28455718, ..., -0.1530291 ,
         0.1154583 ,  0.29410136],
       [-0.61285285, -0.2548656 , -0.3678498 , ..., -0.4707147 ,
        -0.72696311, -0.47432802],
       [-0.70915757, -2.06497797, -0.9941605 , ..., -0.53588098,
         1.51949399, -0.14647818],
       ...,
       [-0.34801487,  0.73246842, -0.3678498 , ..., -0.27521587,
        -0.72696311,  0.79137069],
       [ 0.87987033,  0.81474625,  0.28455718, ...,  0.62082044,
        -0.53975835, -0.15708062],
       [ 0.27796582, -0.41942127,  0.28455718, ...,  0.13207336,
        -1.47578214, -0.71517058]])

In [12]:
x_train_scale, x_test_scaled = (scaler.transform(x_train), scaler.transform(x_test))

In [13]:
from sklearn.linear_model import Lasso

In [14]:
model = Lasso()
model_scaled = Lasso()
model.fit(x_train,y_train)
model_scaled.fit(x_train_scale,y_train)

C:\Users\S T E V E N\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4.523431575059091e+18, tolerance: 9546471001925496.0
  positive)


Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [15]:
#Los modelos de regresión no se ven afectados por el escalamiento de las features. Los de clasificación sí.
print(model.score(x_test,y_test))
print(model_scaled.score(x_test_scaled,y_test))

0.8500724882603596
0.8500724903025733


#### Simplificar las transformaciones con pipelines


Para hacer el código más reproducible, y para evitar tener que aplicar multiples veces una misma transformación es recomendable utilizar  sklearn.pipeline.make_pipeline que permite encadenar transformaciones en los modelos.


In [16]:
from sklearn.pipeline import make_pipeline

In [17]:
model_scaled = make_pipeline(StandardScaler(), Lasso())
model_scaled.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('lasso',
                 Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                       max_iter=1000, normalize=False, positive=False,
                       precompute=False, random_state=None, selection='cyclic',
                       tol=0.0001, warm_start=False))],
         verbose=False)

In [18]:
print(model_scaled.score(x_test,y_test))

0.8500724903025733


#### Crear nuevas features de forma automática

In [19]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
from sklearn.preprocessing import PolynomialFeatures

In [21]:
transformer = PolynomialFeatures(2)
transformer

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False,
                   order='C')

In [22]:
transformer.fit_transform(a)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [23]:
x.shape

(4061, 8)

Fit and transform se hacen al mismo tiempo con fit_transform, fit_trasform puede generar mas fiatures, puede ser riesgoso

In [24]:
transformer = PolynomialFeatures(2)
transformer.fit_transform(x).shape

(4061, 45)

In [25]:
model_poly = make_pipeline(PolynomialFeatures(2),Lasso())
model_poly.fit(x_train,y_train)
model_poly.score(x_test,y_test)

C:\Users\S T E V E N\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4.682498160101331e+18, tolerance: 9546471001925496.0
  positive)


0.8096398406060525

In [26]:
model = Lasso()
model.fit(x_train,y_train)
model.score(x_test,y_test)

C:\Users\S T E V E N\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4.523431575059091e+18, tolerance: 9546471001925496.0
  positive)


0.8500724882603596

# Creando feature catgoricas

Encoding one-hot

In [27]:
data = pd.DataFrame([['Chile','Colombia','Colombia'],['Hombre','Mujer','Hombre','Mujer']])
data = data.T
data.columns = pd.Index(['pais','genero'])
data

pais  genero
0     Chile  Hombre
1  Colombia   Mujer
2  Colombia  Hombre
3      None   Mujer

In [28]:
pd.get_dummies(data)

pais_Chile  pais_Colombia  genero_Hombre  genero_Mujer
0           1              0              1             0
1           0              1              0             1
2           0              1              1             0
3           0              0              0             1

In [29]:
movies_obj = pd.read_csv('./movies_obj.csv')
movies_obj

movie_title             color  \
0                                               Avatar              Color   
1             Pirates of the Caribbean: At World's End              Color   
2                                              Spectre              Color   
3                                The Dark Knight Rises              Color   
4     Star Wars: Episode VII - The Force Awakens    ...               NaN   
5                                          John Carter              Color   
6                                         Spider-Man 3              Color   
7                                              Tangled              Color   
8                              Avengers: Age of Ultron              Color   
9               Harry Potter and the Half-Blood Prince              Color   
10                  Batman v Superman: Dawn of Justice              Color   
11                                    Superman Returns              Color   
12                                   Quantum of Solace              Color   
13          Pirates of the Caribbean: Dead Man's Chest              Color   
14                                     The Lone Ranger              Color   
15                                        Man of Steel              Color   
16            The Chronicles of Narnia: Prince Caspian              Color   
17                                        The Avengers              Color   
18         Pirates of the Caribbean: On Stranger Tides              Color   
19                                      Men in Black 3              Color   
20           The Hobbit: The Battle of the Five Armies              Color   
21                              The Amazing Spider-Man              Color   
22                                          Robin Hood              Color   
23                 The Hobbit: The Desolation of Smaug              Color   
24                                  The Golden Compass              Color   
25                                           King Kong              Color   
26                                             Titanic              Color   
27                          Captain America: Civil War              Color   
28                                          Battleship              Color   
29                                      Jurassic World              Color   
...                                                 ...               ...   
5013                                            Manito              Color   
5014                                           Rampage              Color   
5015                                           Slacker    Black and White   
5016                                       Dutch Kills              Color   
5017                                         Dry Spell              Color   
5018                                          Flywheel              Color   
5019                                            Exeter              Color   
5020                                        The Ridges                NaN   
5021                                   The Puffy Chair              Color   
5022                              Stories of Our Lives    Black and White   
5023                                  Breaking Upwards              Color   
5024                          All Superheroes Must Die              Color   
5025                                    Pink Flamingos              Color   
5026                                             Clean              Color   
5027                                        The Circle              Color   
5028                                       Tin Can Man    Black and White   
5029                                          The Cure              Color   
5030                                    On the Downlow              Color   
5031                      Sanctuary; Quite a Conundrum              Color   
5032                                              Bang              Color   
5033                                    

#### Es util si el top 20 se encuentra en gran parte de los datos.

In [30]:
movies_obj.apply(pd.Series.nunique).sort_values()

color                2
content_rating      18
language            47
country             65
genres             914
actor_1_name      2097
director_name     2398
actor_2_name      3032
actor_3_name      3521
plot_keywords     4760
movie_title       4917
dtype: int64

# Encoding Binario

In [31]:
#!pip install category_encoders

In [32]:
categorias = pd.read_csv('./categoricals.csv').set_index('Unnamed: 0')
categorias.head()

actor_1_name      director_name
Unnamed: 0                                    
0               CCH Pounder      James Cameron
1               Doug Walker        Doug Walker
2               Johnny Depp     Gore Verbinski
3           Christoph Waltz         Sam Mendes
4                 Tom Hardy  Christopher Nolan

In [33]:
categorias = categorias.reset_index(drop=True).fillna(0)
categorias

actor_1_name       director_name
0              CCH Pounder       James Cameron
1              Doug Walker         Doug Walker
2              Johnny Depp      Gore Verbinski
3          Christoph Waltz          Sam Mendes
4                Tom Hardy   Christopher Nolan
5              Johnny Depp      Gore Verbinski
6             Daryl Sabara      Andrew Stanton
7             Brad Garrett        Nathan Greno
8             J.K. Simmons           Sam Raimi
9             J.K. Simmons           Sam Raimi
10         Chris Hemsworth         Joss Whedon
11       Robert Downey Jr.       Anthony Russo
12            Henry Cavill         Zack Snyder
13            Aidan Turner       Peter Jackson
14            Alan Rickman         David Yates
15            Aidan Turner       Peter Jackson
16            Aidan Turner       Peter Jackson
17             Johnny Depp        Rob Marshall
18            Kevin Spacey        Bryan Singer
19      Giancarlo Giannini        Marc Forster
20             Johnny Depp      Gore Verbinski
21            Henry Cavill         Zack Snyder
22          Peter Dinklage      Andrew Adamson
23              Emma Stone           Marc Webb
24     Bryce Dallas Howard     Colin Trevorrow
25         Glenn Morshower         Michael Bay
26             Bingbing Li         Michael Bay
27            Hugh Jackman        Brett Ratner
28               Mark Addy        Ridley Scott
29             Liam Neeson          Peter Berg
...                    ...                 ...
4074  Marcello Mastroianni       Bruno Barreto
4075           Lena Dunham         Lena Dunham
4076             Lin Shaye      William Eubank
4077                     0           Jem Cohen
4078        Paul Schneider  David Gordon Green
4079        Derick Martini        Kevin Jordan
4080             Zoe Kazan   Bradley Rust Gray
4081        Elissa Dowling        Travis Legge
4082           Ringo Starr     Martin Scorsese
4083     Joseph Campanella          Mike Bruce
4084       Andrew Bujalski     Andrew Bujalski
4085       Andrew Bujalski     Andrew Bujalski
4086        Michael Smiley        Ben Wheatley
4087           Jason Mewes         Kevin Smith
4088            Don Brooks       James Bidgood
4089         Stacy Edwards         Neil LaBute
4090        Tommy Pallotta   Richard Linklater
4091          Mark Duplass         Jay Duplass
4092      Zoe Lister-Jones          Daryl Wein
4093                Divine         John Waters
4094         Maggie Cheung     Olivier Assayas
4095   Tatiana Suarez-Pico        Tadeo Garcia
4096          Peter Greene     Ash Baron-Cohen
4097           Kerry Bishé        Edward Burns
4098       Carlos Gallardo    Robert Rodriguez
4099         Shane Carruth       Shane Carruth
4100           Ian Gamazon    Neill Dela Llana
4101        Richard Jewell     Anthony Vallone
4102             Alan Ruck         Daniel Hsia
4103           John August            Jon Gunn

[4104 rows x 2 columns]

In [34]:
X_binenc = pd.concat([x, categorias], axis=1)

In [35]:
X_binenc.shape

(4104, 10)

In [36]:
import category_encoders as ce
encoder = ce.BinaryEncoder(cols=['actor_1_name','director_name'])
encoder

BinaryEncoder(cols=['actor_1_name', 'director_name'], drop_invariant=False,
              handle_missing='value', handle_unknown='value', mapping=None,
              return_df=True, verbose=0)

In [37]:
encoder.fit_transform(X_binenc).shape

(4104, 32)

In [38]:
X_binenc = encoder.fit_transform(X_binenc)
X_binenc.head()

production_budget   title_year  aspect_ratio    duration  \
0        425000000.0  2009.000000      1.780000  178.000000   
1        306000000.0  2002.102628      2.126683  108.552703   
2        300000000.0  2007.000000      2.350000  169.000000   
3        300000000.0  2015.000000      2.350000  148.000000   
4        275000000.0  2012.000000      2.350000  164.000000   

   cast_total_facebook_likes        budget  imdb_score         gross  \
0                     4834.0  2.370000e+08         7.9  7.605058e+08   
1                      143.0  3.712339e+07         7.1  4.819001e+07   
2                    48350.0  3.000000e+08         7.1  3.094042e+08   
3                    11700.0  2.450000e+08         6.8  2.000742e+08   
4                   106759.0  2.500000e+08         8.5  4.481306e+08   

   actor_1_name_0  actor_1_name_1  ...  director_name_2  director_name_3  \
0               0               0  ...                0                0   
1               0               0  ...                0                0   
2               0               0  ...                0                0   
3               0               0  ...                0                0   
4               0               0  ...                0                0   

   director_name_4  director_name_5  director_name_6  director_name_7  \
0                0                0                0                0   
1                0                0                0                0   
2                0                0                0                0   
3                0                0                0                0   
4                0                0                0                0   

   director_name_8  director_name_9  director_name_10  director_name_11  
0                0                0                 0                 1  
1                0                0                 1                 0  
2                0                0                 1                 1  
3                0                1                 0                 0  
4                0                1                 0                 1  

[5 rows x 32 columns]

In [39]:
y.shape

(4061,)

In [40]:
X_binenc.shape

(4104, 32)

In [41]:
X_binenc = X_binenc[X_binenc['production_budget'].notnull()]
X_binenc.shape

(4061, 32)

In [42]:
Xb_train, Xb_test, y_train, y_test = train_test_split(X_binenc,y)

In [43]:
X_train, X_test = (Xb_train[x.columns], Xb_test[x.columns])

In [44]:
model_binenc = Lasso()
model = Lasso()

In [45]:
model_binenc.fit(Xb_train, y_train)
model.fit(X_train, y_train)

C:\Users\S T E V E N\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.3036486191982607e+18, tolerance: 9384279301811862.0
  positive)


Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [46]:
print(model_binenc.score(Xb_test, y_test))
print(model.score(X_test, y_test))

0.782778571196947
0.7803605049879538


# Conocimiento experto