In [1]:
import numpy as np

In [6]:
#Crear arrays
a1 = np.array([9,8,7,6,5,4,3,2,1])
display(a1,type(a1))

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

numpy.ndarray

In [8]:
#Crear un rango en numpy
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Crear un lista de dos dimensiones, pre-rellenadas con zeron
#Crear un lista de dos dimensiones, pre-rellenadas con unos
a3 = np.zeros((2,3))
a4 = np.ones((2,3))
display(a3,a4,type(a3),type(4))

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

numpy.ndarray

int

np.linspace(a,b,n) <font color = 'blue'>Crear una funcion que permite crear arrays de una dimension, de largo n, y que contienen puntos a y b, distanciados de forma regular. La distancia entre cada punto sera de (b-a)/(n-1)</font>

In [12]:
a5 = np.linspace(0,1,11)
a5

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
a5.dtype

dtype('float64')

In [14]:
#Acceder a la dimension
a1.shape

(9,)

In [15]:
a3.shape

(2, 3)

In [16]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape,a2D.shape)

(3,)

(1, 3)

In [17]:
# Son los dos arreglos iguales
np.array_equal(a1D,a2D)

False

In [18]:
#Reshaping
new_dims = (1,a1D.shape[0])
a = a1D.reshape(new_dims)

In [19]:
np.array_equal(a,a2D)

True

In [20]:
#Acceso a lementos y SLicing
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [21]:
a[0,0]

1

In [22]:
a[2,1]

10

In [23]:
a = np.arange(10)
b = np.eye(3)
display(a)
display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#Acceder a los 5 primeros
a[:5]

array([0, 1, 2, 3, 4])

In [25]:
b[0:3,1]

array([0., 1., 0.])

In [30]:
b[2,0:3]

array([0., 0., 1.])